### ISSUE TITLE
Website is not responsive 

### ISSUE THREAD

**Issue by samikshakute** [samikshakute/samikshakute.github.io#1]

**Comment by Upendr-sahni** [comment]
hey @samikshakute i want to work on this issue, can you assign this issue to me?

**Comment by lewisushindi** [comment]
hey! visited the website link, can you give more information on how you want the website to look like at larger, medium and smaller devices.

**Comment by samikshakute** [comment]
@lewisushindi I want the website to look similar to what it's looking now for medium and smaller devices.

**Comment by lewisushindi** [comment]
okay, I can help you with that

**Comment by lewisushindi** [comment]
assign
