### ISSUE TITLE
nav menu link open in new window

### ISSUE THREAD

**Issue by devvsakib** [samikshakute/samikshakute.github.io#2]
RN, the website's menu opens in a new tab. The menu should not open a new lab. Remove the target from the link.
![image](https://user-images.githubusercontent.com/88339569/222896233-a889c28a-da02-42b1-9405-7386f6f96529.png)

Instead of using target here, use it in the social link
![image](https://user-images.githubusercontent.com/88339569/222896250-e07ddb0a-bfa6-4d86-8e4d-b4abcd1be125.png)

**Comment by samikshakute** [comment]
@devvsakib Thank you for your suggestion. Will make the necessary changes.
