### ISSUE TITLE
website need to recreate

### ISSUE THREAD

**Issue by devvsakib** [samikshakute/samikshakute.github.io#3]
In the header tag, put them.
![image](https://user-images.githubusercontent.com/88339569/222896483-e080364c-9529-40ba-9200-5fd3e3c49a63.png)

use only these CSS,:

header:
```css
display: flex;
flex-direction: column;
align-items: center;
justify-content: center;
gap: 2rem;
text-align: center;
height: 76vh;
```

img:
```css
width: 15%;
```

description:
```css
color: white
```

links:
```css
justify-content: center;
display: flex;
```

result:
![image](https://user-images.githubusercontent.com/88339569/222896567-6df65021-01ce-4ab0-a64e-0a611926bc16.png)

Make it responsive for  mobile, tablet. 
Bonus Point: Links are responsive

**Comment by samikshakute** [comment]
@devvsakib This changes the image and text size when trying to change the resolution. The size must not vary.
